
import React, { useState } from 'react';
import { Bell, Heart, MessageCircle, UserPlus, ShieldCheck, MoreHorizontal, Check, Trash2, Filter, AlertTriangle, ChevronRight, Settings, CheckCircle2, FileText, ExternalLink, Zap, BookOpen, BrainCircuit, Clock } from 'lucide-react';
import { useLanguage } from '../contexts/LanguageContext';
import DocumentPreviewModal from './DocumentPreviewModal';

// Types
type NotificationType = 'like' | 'comment' | 'follow' | 'mention' | 'system' | 'gov_alert' | 'security' | 'deep_reply';

interface Notification {
  id: number;
  type: NotificationType;
  user?: {
    name: string;
    avatar: string;
    isOfficial?: boolean;
  };
  content: {
    title?: string;
    body: string;
    highlight?: string;
  };
  time: string;
  isRead: boolean;
  priority?: 'high' | 'normal' | 'low';
}

const NotificationsView: React.FC = () => {
  const { t, dir } = useLanguage();
  const [activeTab, setActiveTab] = useState<'all' | 'system' | 'mentions'>('all');
  const [activeMenuId, setActiveMenuId] = useState<number | null>(null);
  const [viewingDoc, setViewingDoc] = useState<any>(null);

  // SCENARIO 3: SOFT RETENTION - DAILY DIGEST STATE
  const [showDailyDigest, setShowDailyDigest] = useState(false); // Default to false if no data

  const [notifications, setNotifications] = useState<Notification[]>([]);

  const filteredNotifications = notifications.filter(n => {
    if (activeTab === 'system') return ['system', 'gov_alert', 'security'].includes(n.type);
    if (activeTab === 'mentions') return ['comment', 'mention', 'like', 'follow', 'deep_reply'].includes(n.type);
    return true;
  });

  const handleMarkAsRead = (id: number) => {
    setNotifications(prev => prev.map(n => n.id === id ? { ...n, isRead: true } : n));
    setActiveMenuId(null);
  };

  const handleDelete = (id: number) => {
    setNotifications(prev => prev.filter(n => n.id !== id));
    setActiveMenuId(null);
  };

  const markAllRead = () => {
    setNotifications(prev => prev.map(n => ({ ...n, isRead: true })));
  };

  const handleViewDocument = (notif: Notification) => {
    // Determine doc content based on notification
    const docData = {
      title: notif.content.title || "Official Notification",
      ref: notif.content.highlight || `REF-${new Date().getFullYear()}-${Math.floor(Math.random() * 10000)}`,
      date: new Date().toLocaleDateString(),
      recipient: "Sarah Jenkins",
      id: "849-221-9901",
      status: 'Approved' as any,
      body: "This is an official automated notification generated by the central system regarding your recent activity."
    };
    
    setViewingDoc(docData);
    setActiveMenuId(null);
    if (!notif.isRead) handleMarkAsRead(notif.id);
  };

  const getIcon = (type: NotificationType) => {
    switch (type) {
      case 'like': return <Heart size={16} className="text-white fill-white" />;
      case 'comment': return <MessageCircle size={16} className="text-white fill-white" />;
      case 'deep_reply': return <BrainCircuit size={16} className="text-white" />; // Scenario 4
      case 'follow': return <UserPlus size={16} className="text-white" />;
      case 'gov_alert': return <ShieldCheck size={18} className="text-white" />;
      case 'security': return <ShieldCheck size={18} className="text-white" />;
      default: return <Bell size={16} className="text-white" />;
    }
  };

  const getIconBg = (type: NotificationType) => {
    switch (type) {
      case 'like': return 'bg-red-500';
      case 'comment': return 'bg-blue-500';
      case 'deep_reply': return 'bg-indigo-600'; // Scenario 4 Distinct Color
      case 'follow': return 'bg-brand-blue';
      case 'gov_alert': return 'bg-brand-green';
      case 'security': return 'bg-slate-800';
      default: return 'bg-slate-400';
    }
  };

  // SCENARIO 3: DAILY DIGEST COMPONENT
  const DailyBriefingCard = () => (
    <div className="bg-gradient-to-r from-slate-900 to-indigo-950 rounded-2xl p-6 text-white relative overflow-hidden mb-6 shadow-xl group">
       {/* Background */}
       <div className="absolute top-0 right-0 w-40 h-40 bg-brand-yellow/10 rounded-full blur-3xl -mr-10 -mt-10"></div>
       <div className="absolute bottom-0 left-0 w-32 h-32 bg-brand-green/10 rounded-full blur-2xl"></div>
       
       <div className="relative z-10">
          <div className="flex justify-between items-start mb-4">
             <div className="flex items-center gap-3">
                <div className="p-3 bg-white/10 rounded-xl backdrop-blur-sm border border-white/10">
                   <BookOpen size={24} className="text-brand-yellow" />
                </div>
                <div>
                   <h3 className="font-display font-bold text-lg leading-tight">Your Daily Briefing</h3>
                   <p className="text-slate-400 text-xs mt-0.5">Summary</p>
                </div>
             </div>
             <button onClick={() => setShowDailyDigest(false)} className="text-slate-400 hover:text-white transition-colors">
                <Settings size={16} />
             </button>
          </div>

          <div className="space-y-3">
             <p className="text-sm text-slate-300">No major updates today.</p>
          </div>
       </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-slate-50 pb-20">
      
      {/* Header */}
      <div className="bg-white p-6 border-b border-slate-200 sticky top-0 z-30">
        <div className="flex justify-between items-center mb-4">
          <h1 className="text-2xl font-display font-bold text-slate-900">{t('nav.notifications')}</h1>
          <button 
            onClick={markAllRead}
            className="text-brand-blue text-sm font-bold hover:bg-brand-light px-3 py-1.5 rounded-lg transition-colors"
          >
            Mark all as read
          </button>
        </div>

        {/* Filter Tabs */}
        <div className="flex gap-2 overflow-x-auto scrollbar-hide">
          {[
            { id: 'all', label: 'All', icon: Bell },
            { id: 'system', label: 'System & Gov', icon: ShieldCheck },
            { id: 'mentions', label: 'Mentions', icon: MessageCircle },
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-full text-sm font-bold whitespace-nowrap transition-all ${
                activeTab === tab.id 
                  ? 'bg-slate-900 text-white shadow-md' 
                  : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
              }`}
            >
              <tab.icon size={16} />
              <span>{tab.label}</span>
            </button>
          ))}
        </div>
      </div>

      {/* List */}
      <div className="max-w-2xl mx-auto p-4 md:p-6">
        
        {/* Soft Retention: Daily Briefing Card */}
        {showDailyDigest && activeTab === 'all' && <DailyBriefingCard />}

        {filteredNotifications.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 text-slate-400">
            <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center mb-4">
              <Bell size={24} />
            </div>
            <p className="text-sm font-medium">No new notifications</p>
          </div>
        ) : (
          <div className="divide-y divide-slate-100 bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
            {filteredNotifications.map((notif) => (
              <div 
                key={notif.id}
                className={`relative p-5 transition-all group ${
                  notif.isRead ? 'bg-white hover:bg-slate-50' : (notif.type === 'deep_reply' ? 'bg-indigo-50/50 hover:bg-indigo-50' : 'bg-brand-blue/5 hover:bg-brand-blue/10')
                }`}
                onClick={() => setActiveMenuId(null)}
              >
                 {/* ... Notification Item ... */}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Document Viewer Modal */}
      {viewingDoc && (
        <DocumentPreviewModal 
          data={viewingDoc} 
          onClose={() => setViewingDoc(null)} 
        />
      )}

    </div>
  );
};

export default NotificationsView;
